# Generated by Django 5.1.7 on 2026-03-17 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_industries', models.TextField(help_text='Comma-separated list of industries')),
                ('min_company_size', models.PositiveIntegerField(default=1)),
                ('max_company_size', models.PositiveIntegerField(default=1000)),
                ('target_roles', models.TextField(help_text='Comma-separated list of job roles or seniority')),
                ('target_regions', models.TextField(blank=True, help_text='Comma-separated list of regions/countries', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
